Feature/mnv flags
cancerit/cgpCaVEManPostProcessing pull request #43
Opened 2022-04-07 11:19 UTC by davidrajones

2022-04-08 13:14 UTC, rulixxx requested changes

2022-04-08 13:25 UTC, rulixxx commented
Nothing major :

Some indentation issues.
I noticed you updated some of the licences ( not sure how that is handled). Some files seem to have the old date.

Don't forget to update the README with the new option

Otherwise code is pretty good, your use of references in perl is quite impressive! ( Had to lookup some things ;)  )

Have a good easter holiday

2022-04-19 15:07 UTC, davidrajones commented on bin/cgpFlagCaVEMan.pl
> +        return $flagger->getCavemanMatchedNormalResult($vcf,$x,$index);
d588932

2022-04-19 15:09 UTC, davidrajones commented on t/3_cgpFlagCaVEMan.t
> +  unlink($test_out_mnv_file);
a113854

2022-04-19 15:14 UTC, davidrajones commented on t/5_genomePostProcessor.t
>                                                                              'depthCutoffProportion' => (1/2),
97a2d8f

2022-04-19 15:14 UTC, davidrajones commented on t/4_exomePostProcessor.t
> +                          'depthCutoffProportion' => (1/2),
97a2d8f

2022-07-25 09:05 UTC, merged